earthdata:
  # Endpoints for Earthdata.  These must remain in sync, because for instance ECHO SIT can't accept tokens from URS ops
  ops:
    urs_root: "https://urs.earthdata.nasa.gov"
    echo_root: "https://api.echo.nasa.gov"
    cmr_root: "https://cmr.earthdata.nasa.gov"
    edsc_root: "https://search.earthdata.nasa.gov"
  uat:
    urs_root: "https://uat.urs.earthdata.nasa.gov"
    echo_root: "https://api-test.echo.nasa.gov"
    cmr_root: "https://cmr.uat.earthdata.nasa.gov"
    edsc_root: "https://search.uat.earthdata.nasa.gov"
  sit:
    urs_root: "https://sit.urs.earthdata.nasa.gov"
    echo_root: "https://testbed.echo.nasa.gov"
    cmr_root: "https://cmr.sit.earthdata.nasa.gov"
    edsc_root: "https://search.sit.earthdata.nasa.gov"
    launchpad_root: "https://apps.launchpad-sbx.nasa.gov"

# Every (MMT, URS) environment pair has a different client id.
urs:
  production:
    "https://urs.earthdata.nasa.gov": "QCuabaWMrGyq0OvCj0X-pg"
  uat:
    "https://uat.urs.earthdata.nasa.gov": "zFb4tV63ET-V6-oRnDKmJg"
  sit:
    "https://sit.urs.earthdata.nasa.gov": "81FEem91NlTQreWv2UgtXQ"
  development:
    "https://sit.urs.earthdata.nasa.gov": "81FEem91NlTQreWv2UgtXQ"
  test:
    "https://sit.urs.earthdata.nasa.gov": "81FEem91NlTQreWv2UgtXQ"

echo_soap:
  services:
    authentication:
      wsdl: "echo-wsdl/v10/AuthenticationService.wsdl"
      path: "echo-v10/AuthenticationServicePortImpl"
    provider:
      wsdl: "echo-wsdl/v10/ProviderService.wsdl"
      path: "echo-v10/ProviderServicePortImpl"
    data_management:
      wsdl: "echo-wsdl/v10/DataManagementService.wsdl"
      path: "echo-v10/DataManagementServicePortImpl"
    service_management:
      wsdl: "echo-wsdl/v10/ServiceManagementService.wsdl"
      path: "echo-v10/ServiceManagementServicePortImpl"
    order_management:
      wsdl: "echo-wsdl/v10/OrderManagementService.wsdl"
      path: "echo-v10/OrderManagementServicePortImpl"
    order_processing:
      wsdl: "echo-wsdl/v10/OrderProcessingService.wsdl"
      path: "echo-v10/OrderProcessingServicePortImpl"
    user_service:
      wsdl: "echo-wsdl/v10/UserService.wsdl"
      path: "echo-v10/UserServicePortImpl"
